# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:27:13+00:00

from __future__ import annotations

from datetime import date, datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel, SecretStr


class AssessmentCode(Enum):
    Excluded = 'Excluded'
    EligibleJobHolder = 'EligibleJobHolder'
    NonEligibleJobHolder = 'NonEligibleJobHolder'
    EntitledWorker = 'EntitledWorker'


class AssessmentEvent(Enum):
    NonEnrolmentEvent = 'NonEnrolmentEvent'
    AutomaticEnrolment = 'AutomaticEnrolment'
    OptIn = 'OptIn'
    VoluntaryJoiner = 'VoluntaryJoiner'
    ContractualEnrolment = 'ContractualEnrolment'


class AssessmentOverride(Enum):
    None_ = 'None'
    OptOut = 'OptOut'
    OptIn = 'OptIn'
    VoluntaryJoiner = 'VoluntaryJoiner'
    ContractualPension = 'ContractualPension'
    CeasedMembership = 'CeasedMembership'
    Leaver = 'Leaver'
    Excluded = 'Excluded'


class AssessmentResult(Enum):
    Inconclusive = 'Inconclusive'
    NoChange = 'NoChange'
    Enrol = 'Enrol'
    Exit = 'Exit'


class AEAssessment1(BaseModel):
    Age: Optional[int] = Field(
        None, description="The a e assessments' age", title='Age'
    )
    AssessmentCode_1: Optional[AssessmentCode] = Field(
        None,
        alias='AssessmentCode',
        description="The a e assessments' assessment code",
        title='AssessmentCode',
    )
    AssessmentDate: Optional[date] = Field(
        None, description="The a e assessments' assessment date", title='AssessmentDate'
    )
    AssessmentEvent_1: Optional[AssessmentEvent] = Field(
        None,
        alias='AssessmentEvent',
        description="The a e assessments' assessment event",
        title='AssessmentEvent',
    )
    AssessmentOverride_1: Optional[AssessmentOverride] = Field(
        None,
        alias='AssessmentOverride',
        description="The a e assessments' assessment override",
        title='AssessmentOverride',
    )
    AssessmentResult_1: Optional[AssessmentResult] = Field(
        None,
        alias='AssessmentResult',
        description="The a e assessments' assessment result",
        title='AssessmentResult',
    )
    IsMemberOfAlternativePensionScheme: Optional[bool] = Field(
        None,
        description="The a e assessments' is member of alternative pension scheme",
        title='IsMemberOfAlternativePensionScheme',
    )
    OptOutWindowEndDate: Optional[date] = Field(
        None,
        description="The a e assessments' opt out window end date",
        title='OptOutWindowEndDate',
    )
    QualifyingEarnings: Optional[float] = Field(
        None,
        description="The a e assessments' qualifying earnings",
        title='QualifyingEarnings',
    )
    ReenrolmentDate: Optional[date] = Field(
        None,
        description="The a e assessments' reenrolment date",
        title='ReenrolmentDate',
    )
    StatePensionAge: Optional[int] = Field(
        None,
        description="The a e assessments' state pension age",
        title='StatePensionAge',
    )
    StatePensionDate: Optional[date] = Field(
        None,
        description="The a e assessments' state pension date",
        title='StatePensionDate',
    )
    TaxPeriod: Optional[int] = Field(
        None, description="The a e assessments' tax period", title='TaxPeriod'
    )
    TaxYear: Optional[int] = Field(
        None, description="The a e assessments' tax year", title='TaxYear'
    )


class AEAssessment(BaseModel):
    AEAssessment: Optional[AEAssessment1] = Field(None, title='AEAssessment')


class ApplicationSecret(RootModel[Any]):
    root: Any


class BatchItemBase1(BaseModel):
    field_Href: Optional[str] = Field(
        None, alias='@Href', description="The batch item bases' href", title='@Href'
    )


class BatchItemBase(BaseModel):
    BatchItemBase: Optional[BatchItemBase1] = Field(None, title='BatchItemBase')


class DELETEItem(BaseModel):
    field_Href: Optional[str] = Field(
        None, alias='@Href', description="The batch item bases' href", title='@Href'
    )


class Instructions(BaseModel):
    DELETE: Optional[List[DELETEItem]] = None


class BatchJobInstruction1(BaseModel):
    HoldingDate: Optional[datetime] = Field(
        None,
        description="The batch job instructions' holding date",
        title='HoldingDate',
    )
    Instructions_1: Optional[Instructions] = Field(
        None,
        alias='Instructions',
        description="The batch job instructions' instructions",
        title='DELETE',
    )
    ValidateOnly: Optional[bool] = Field(
        None,
        description="The batch job instructions' validate only",
        title='ValidateOnly',
    )


class BatchJobInstruction(BaseModel):
    BatchJobInstruction: Optional[BatchJobInstruction1] = Field(
        None, title='BatchJobInstruction'
    )


class PayFrequency(Enum):
    Monthly = 'Monthly'
    Weekly = 'Weekly'


class UOM(Enum):
    NotSet = 'NotSet'
    Minute = 'Minute'
    Hour = 'Hour'
    Day = 'Day'
    Week = 'Week'
    Month = 'Month'
    Year = 'Year'
    Unit = 'Unit'


class CisInstruction1(BaseModel):
    CisLineTag: Optional[str] = Field(
        None, description="The cis instructions' cis line tag", title='CisLineTag'
    )
    CisLineType: Optional[str] = Field(
        None, description="The cis instructions' cis line type", title='CisLineType'
    )
    Description: Optional[str] = Field(
        None, description="The cis instructions' description", title='Description'
    )
    PayFrequency_1: Optional[PayFrequency] = Field(
        None,
        alias='PayFrequency',
        description="The cis instructions' pay frequency",
        title='PayFrequency',
    )
    PeriodEnd: Optional[int] = Field(
        None, description="The cis instructions' period end", title='PeriodEnd'
    )
    PeriodStart: Optional[int] = Field(
        None, description="The cis instructions' period start", title='PeriodStart'
    )
    TaxYearEnd: Optional[int] = Field(
        None, description="The cis instructions' tax year end", title='TaxYearEnd'
    )
    TaxYearStart: Optional[int] = Field(
        None, description="The cis instructions' tax year start", title='TaxYearStart'
    )
    UOM_1: Optional[UOM] = Field(
        None, alias='UOM', description="The cis instructions' u o m", title='UOM'
    )
    Units: Optional[float] = Field(
        None, description="The cis instructions' units", title='Units'
    )
    VAT: Optional[float] = Field(
        None, description="The cis instructions' v a t", title='VAT'
    )
    Value: Optional[float] = Field(
        None, description="The cis instructions' value", title='Value'
    )


class CisInstruction(BaseModel):
    CisInstruction: Optional[CisInstruction1] = Field(None, title='CisInstruction')


class Employer(BaseModel):
    field_href: Optional[str] = Field(
        None, alias='@href', description="The links' href", title='@href'
    )
    field_rel: Optional[str] = Field(
        None, alias='@rel', description="The links' target type", title='@rel'
    )
    field_title: Optional[str] = Field(
        None, alias='@title', description="The links' title", title='@title'
    )


class SubContractorItem(BaseModel):
    field_href: Optional[str] = Field(
        None, alias='@href', description="The links' href", title='@href'
    )
    field_rel: Optional[str] = Field(
        None, alias='@rel', description="The links' target type", title='@rel'
    )
    field_title: Optional[str] = Field(
        None, alias='@title', description="The links' title", title='@title'
    )


class SubContractors(BaseModel):
    SubContractor: Optional[List[SubContractorItem]] = None


class CisJobInstructionBase1(BaseModel):
    Employer_1: Optional[Employer] = Field(
        None,
        alias='Employer',
        description="The cis job instruction bases' employer",
        title='Employer',
    )
    HoldingDate: Optional[datetime] = Field(
        None,
        description="The cis job instruction bases' holding date",
        title='HoldingDate',
    )
    SubContractors_1: Optional[SubContractors] = Field(
        None,
        alias='SubContractors',
        description="The cis job instruction bases' sub contractors",
        title='SubContractor',
    )


class CisJobInstructionBase(BaseModel):
    CisJobInstructionBase: Optional[CisJobInstructionBase1] = Field(
        None, title='CisJobInstructionBase'
    )


class TaxTreatment(Enum):
    Taxable = 'Taxable'
    NonTaxable = 'NonTaxable'
    Notional = 'Notional'
    Materials = 'Materials'


class CisLine1(BaseModel):
    CisDeduction: Optional[float] = Field(
        None, description="The cis lines' cis deduction", title='CisDeduction'
    )
    CisLineType: Optional[str] = Field(
        None, description="The cis lines' cis line type", title='CisLineType'
    )
    Description: Optional[str] = Field(
        None, description="The cis lines' description", title='Description'
    )
    Generated: Optional[datetime] = Field(
        None, description="The cis lines' generated", title='Generated'
    )
    GrossPay: Optional[float] = Field(
        None, description="The cis lines' gross pay", title='GrossPay'
    )
    NominalCodeKey: Optional[str] = Field(
        None, description="The cis lines' nominal code key", title='NominalCodeKey'
    )
    PayFrequency_1: Optional[PayFrequency] = Field(
        None,
        alias='PayFrequency',
        description="The cis lines' pay frequency",
        title='PayFrequency',
    )
    TaxMonth: Optional[int] = Field(
        None, description="The cis lines' tax month", title='TaxMonth'
    )
    TaxPeriod: Optional[int] = Field(
        None, description="The cis lines' tax period", title='TaxPeriod'
    )
    TaxTreatment_1: Optional[TaxTreatment] = Field(
        None,
        alias='TaxTreatment',
        description="The cis lines' tax treatment",
        title='TaxTreatment',
    )
    TaxYear: Optional[int] = Field(
        None, description="The cis lines' tax year", title='TaxYear'
    )
    UOM_1: Optional[UOM] = Field(
        None, alias='UOM', description="The cis lines' u o m", title='UOM'
    )
    UnitRate: Optional[float] = Field(
        None, description="The cis lines' unit rate", title='UnitRate'
    )
    Units: Optional[float] = Field(
        None, description="The cis lines' units", title='Units'
    )
    VAT: Optional[float] = Field(None, description="The cis lines' v a t", title='VAT')


class CisLine(BaseModel):
    CisLine: Optional[CisLine1] = Field(None, title='CisLine')


class NominalCode(BaseModel):
    field_href: Optional[str] = Field(
        None, alias='@href', description="The links' href", title='@href'
    )
    field_rel: Optional[str] = Field(
        None, alias='@rel', description="The links' target type", title='@rel'
    )
    field_title: Optional[str] = Field(
        None, alias='@title', description="The links' title", title='@title'
    )


class CisLineType1(BaseModel):
    Description: Optional[str] = Field(
        None, description="The cis line types' description", title='Description'
    )
    LineType: Optional[str] = Field(
        None, description="The cis line types' line type", title='LineType'
    )
    NominalCode_1: Optional[NominalCode] = Field(
        None,
        alias='NominalCode',
        description="The cis line types' nominal code",
        title='NominalCode',
    )
    TaxTreatment_1: Optional[TaxTreatment] = Field(
        None,
        alias='TaxTreatment',
        description="The cis line types' tax treatment",
        title='TaxTreatment',
    )


class CisLineType(BaseModel):
    CisLineType: Optional[CisLineType1] = Field(None, title='CisLineType')


class CisMessageType(Enum):
    Verification = 'Verification'
    Return = 'Return'


class EmployerCore(BaseModel):
    field_href: Optional[str] = Field(
        None, alias='@href', description="The links' href", title='@href'
    )
    field_rel: Optional[str] = Field(
        None, alias='@rel', description="The links' target type", title='@rel'
    )
    field_title: Optional[str] = Field(
        None, alias='@title', description="The links' title", title='@title'
    )


class TransactionStatus(Enum):
    New = 'New'
    RequestGenerated = 'RequestGenerated'
    CompletedWithError = 'CompletedWithError'
    CompletedWithSuccess = 'CompletedWithSuccess'
    TimeOut = 'TimeOut'


class CisTransaction1(BaseModel):
    CisMessageType_1: Optional[CisMessageType] = Field(
        None,
        alias='CisMessageType',
        description="The cis transactions' cis message type",
        title='CisMessageType',
    )
    EmployerCore_1: Optional[EmployerCore] = Field(
        None,
        alias='EmployerCore',
        description="The cis transactions' employer core",
        title='EmployerCore',
    )
    RequestData: Optional[str] = Field(
        None, description="The cis transactions' request data", title='RequestData'
    )
    ResponseData: Optional[str] = Field(
        None, description="The cis transactions' response data", title='ResponseData'
    )
    TaxYear: Optional[int] = Field(
        None, description="The cis transactions' tax year", title='TaxYear'
    )
    Timestamp: Optional[datetime] = Field(
        None, description="The cis transactions' timestamp", title='Timestamp'
    )
    TransactionStatus_1: Optional[TransactionStatus] = Field(
        None,
        alias='TransactionStatus',
        description="The cis transactions' transaction status",
        title='TransactionStatus',
    )
    TransmissionDate: Optional[datetime] = Field(
        None,
        description="The cis transactions' transmission date",
        title='TransmissionDate',
    )


class CisTransaction(BaseModel):
    CisTransaction: Optional[CisTransaction1] = Field(None, title='CisTransaction')


class Employee(BaseModel):
    field_href: Optional[str] = Field(
        None, alias='@href', description="The links' href", title='@href'
    )
    field_rel: Optional[str] = Field(
        None, alias='@rel', description="The links' target type", title='@rel'
    )
    field_title: Optional[str] = Field(
        None, alias='@title', description="The links' title", title='@title'
    )


class PayRun(BaseModel):
    field_href: Optional[str] = Field(
        None, alias='@href', description="The links' href", title='@href'
    )
    field_rel: Optional[str] = Field(
        None, alias='@rel', description="The links' target type", title='@rel'
    )
    field_title: Optional[str] = Field(
        None, alias='@title', description="The links' title", title='@title'
    )


class Commentary1(BaseModel):
    Created: Optional[datetime] = Field(
        None, description="The commentarys' created", title='Created'
    )
    Detail: Optional[str] = Field(
        None, description="The commentarys' detail", title='Detail'
    )
    Employee_1: Optional[Employee] = Field(
        None,
        alias='Employee',
        description="The commentarys' employee",
        title='Employee',
    )
    PayRun_1: Optional[PayRun] = Field(
        None, alias='PayRun', description="The commentarys' pay run", title='PayRun'
    )


class Commentary(BaseModel):
    Commentary: Optional[Commentary1] = Field(None, title='Commentary')


class MessageTypes(BaseModel):
    Type: Optional[List[Dict[str, Any]]] = None


class MessageItem(BaseModel):
    field_href: Optional[str] = Field(
        None, alias='@href', description="The links' href", title='@href'
    )
    field_rel: Optional[str] = Field(
        None, alias='@rel', description="The links' target type", title='@rel'
    )
    field_title: Optional[str] = Field(
        None, alias='@title', description="The links' title", title='@title'
    )


class MessagesToProcess(BaseModel):
    Message: Optional[List[MessageItem]] = None


class DpsJobInstruction1(BaseModel):
    Apply: Optional[bool] = Field(
        None, description="The dps job instructions' apply", title='Apply'
    )
    Employer_1: Optional[Employer] = Field(
        None,
        alias='Employer',
        description="The dps job instructions' employer",
        title='Employer',
    )
    FromDate: Optional[date] = Field(
        None, description="The dps job instructions' from date", title='FromDate'
    )
    HoldingDate: Optional[datetime] = Field(
        None, description="The dps job instructions' holding date", title='HoldingDate'
    )
    MessageTypes_1: Optional[MessageTypes] = Field(
        None,
        alias='MessageTypes',
        description="The dps job instructions' message types",
        title='Type',
    )
    MessagesToProcess_1: Optional[MessagesToProcess] = Field(
        None,
        alias='MessagesToProcess',
        description="The dps job instructions' messages to process",
        title='Message',
    )
    Retrieve: Optional[bool] = Field(
        None, description="The dps job instructions' retrieve", title='Retrieve'
    )


class DpsJobInstruction(BaseModel):
    DpsJobInstruction: Optional[DpsJobInstruction1] = Field(
        None, title='DpsJobInstruction'
    )


class MessageStatus(Enum):
    Retrieved = 'Retrieved'
    Applied = 'Applied'
    Unresolved = 'Unresolved'
    Ignored = 'Ignored'
    Information = 'Information'


class DpsMessage1(BaseModel):
    FormType: Optional[str] = Field(
        None, description="The dps messages' form type", title='FormType'
    )
    IssueDate: Optional[date] = Field(
        None, description="The dps messages' issue date", title='IssueDate'
    )
    LastUpdated: Optional[datetime] = Field(
        None, description="The dps messages' last updated", title='LastUpdated'
    )
    Message: Optional[str] = Field(
        None, description="The dps messages' message", title='Message'
    )
    MessageStatus_1: Optional[MessageStatus] = Field(
        None,
        alias='MessageStatus',
        description="The dps messages' message status",
        title='MessageStatus',
    )
    MessageType: Optional[str] = Field(
        None, description="The dps messages' message type", title='MessageType'
    )
    ProcessingResult: Optional[str] = Field(
        None,
        description="The dps messages' processing result",
        title='ProcessingResult',
    )
    RetrieveDate: Optional[datetime] = Field(
        None, description="The dps messages' retrieve date", title='RetrieveDate'
    )
    SequenceNumber: Optional[int] = Field(
        None, description="The dps messages' sequence number", title='SequenceNumber'
    )


class DpsMessage(BaseModel):
    DpsMessage: Optional[DpsMessage1] = Field(None, title='DpsMessage')


class AEAssessmentOverride(Enum):
    None_ = 'None'
    OptOut = 'OptOut'
    OptIn = 'OptIn'
    VoluntaryJoiner = 'VoluntaryJoiner'
    ContractualPension = 'ContractualPension'
    CeasedMembership = 'CeasedMembership'
    Leaver = 'Leaver'
    Excluded = 'Excluded'


class AEExclusionReasonCode(Enum):
    OtherNotKnown = 'OtherNotKnown'
    NotAWorker = 'NotAWorker'
    NotUKWorker = 'NotUKWorker'
    TemporaryUKWorker = 'TemporaryUKWorker'
    OutsideAgeRange = 'OutsideAgeRange'
    SingleEmployeeDirector = 'SingleEmployeeDirector'
    CeasedMembershipWithin12Months = 'CeasedMembershipWithin12Months'
    CeasedMembershipBeyond12Months = 'CeasedMembershipBeyond12Months'
    WorkerWULSWithin12Month = 'WorkerWULSWithin12Month'
    WorkerWULSBeyond12Month = 'WorkerWULSBeyond12Month'
    WorkerInNoticePeriod = 'WorkerInNoticePeriod'
    WorkerTaxProtection = 'WorkerTaxProtection'


class Address(BaseModel):
    Address1: Optional[str] = Field(
        None, description="The addresss' line 1", title='Address1'
    )
    Address2: Optional[str] = Field(
        None, description="The addresss' line 2", title='Address2'
    )
    Address3: Optional[str] = Field(
        None, description="The addresss' line 3", title='Address3'
    )
    Address4: Optional[str] = Field(
        None, description="The addresss' line 4", title='Address4'
    )
    Country: Optional[str] = Field(
        None, description="The addresss' country", title='Country'
    )
    Postcode: Optional[str] = Field(
        None, description="The addresss' postcode", title='Postcode'
    )


class BankAccount(BaseModel):
    AccountName: Optional[str] = Field(
        None, description="The bank accounts' account name", title='AccountName'
    )
    AccountNumber: Optional[str] = Field(
        None, description="The bank accounts' account number", title='AccountNumber'
    )
    BranchName: Optional[str] = Field(
        None, description="The bank accounts' branch name", title='BranchName'
    )
    Reference: Optional[str] = Field(
        None, description="The bank accounts' reference", title='Reference'
    )
    SortCode: Optional[str] = Field(
        None, description="The bank accounts' sort code", title='SortCode'
    )


class EmployeePartner(BaseModel):
    FirstName: Optional[str] = Field(
        None, description="The employee partners' first name", title='FirstName'
    )
    Initials: Optional[str] = Field(
        None, description="The employee partners' initials", title='Initials'
    )
    LastName: Optional[str] = Field(
        None, description="The employee partners' last name", title='LastName'
    )
    MiddleName: Optional[str] = Field(
        None, description="The employee partners' middle name", title='MiddleName'
    )
    NiNumber: Optional[str] = Field(
        None, description="The employee partners' ni number", title='NiNumber'
    )


class Gender(Enum):
    Unknown = 'Unknown'
    Male = 'Male'
    Female = 'Female'


class LeaverReason(Enum):
    Resigned = 'Resigned'
    Dismissed = 'Dismissed'
    Redundant = 'Redundant'
    Retired = 'Retired'
    Deceased = 'Deceased'
    LegalCustody = 'LegalCustody'
    Other = 'Other'


class MaritalStatus(Enum):
    NotSet = 'NotSet'
    Single = 'Single'
    Married = 'Married'
    Divorced = 'Divorced'
    Widowed = 'Widowed'


class NicLiability(Enum):
    HasOtherJob = 'HasOtherJob'
    IsFemaleEntitledToReducedRate = 'IsFemaleEntitledToReducedRate'
    IsNotLiable = 'IsNotLiable'
    IsContractedOut = 'IsContractedOut'
    IsFullyLiable = 'IsFullyLiable'
    IsApprentice = 'IsApprentice'
    LeaverBeyond6Weeks = 'LeaverBeyond6Weeks'
    PaymentAfterLeavingIrregular = 'PaymentAfterLeavingIrregular'
    IsFreePortWorker = 'IsFreePortWorker'
    IsNotLiableForEmployerNi = 'IsNotLiableForEmployerNi'


class PaySchedule(BaseModel):
    field_href: Optional[str] = Field(
        None, alias='@href', description="The links' href", title='@href'
    )
    field_rel: Optional[str] = Field(
        None, alias='@rel', description="The links' target type", title='@rel'
    )
    field_title: Optional[str] = Field(
        None, alias='@title', description="The links' title", title='@title'
    )


class PaymentMethod(Enum):
    NotSet = 'NotSet'
    Cash = 'Cash'
    Cheque = 'Cheque'
    BACS = 'BACS'
    FasterPayments = 'FasterPayments'
    Other = 'Other'


class Region(Enum):
    NotSet = 'NotSet'
    England = 'England'
    Scotland = 'Scotland'
    Wales = 'Wales'


class RuleExclusions(Enum):
    None_ = 'None'
    NiMissingPayInstructionRule = 'NiMissingPayInstructionRule'
    TaxMissingPayInstructionRule = 'TaxMissingPayInstructionRule'
    TaxCodeUpliftRule = 'TaxCodeUpliftRule'
    NiSetExpectedLetterRule = 'NiSetExpectedLetterRule'
    NiDateOfBirthChangeRetrospectiveCRule = 'NiDateOfBirthChangeRetrospectiveCRule'
    NiDefermentStatusChangeRule = 'NiDefermentStatusChangeRule'
    NiEndContractedOutTransferRule = 'NiEndContractedOutTransferRule'
    PaymentAfterLeavingTaxCodeRule = 'PaymentAfterLeavingTaxCodeRule'
    LeaverEndInstructionsRule = 'LeaverEndInstructionsRule'
    P45StudentLoanInstructionRule = 'P45StudentLoanInstructionRule'
    P45TaxInstructionRule = 'P45TaxInstructionRule'
    P45YtdTaxRule = 'P45YtdTaxRule'
    YtdInstructionRule = 'YtdInstructionRule'
    TaxCodeRegionChangeRule = 'TaxCodeRegionChangeRule'
    AutoEnrolmentStatusChangeRule = 'AutoEnrolmentStatusChangeRule'
    EmployeeDeceasedRule = 'EmployeeDeceasedRule'
    BenefitInstructionAutoEndRule = 'BenefitInstructionAutoEndRule'


class Seconded(Enum):
    NotSet = 'NotSet'
    Stay183DaysOrMore = 'Stay183DaysOrMore'
    StayLessThan183Days = 'StayLessThan183Days'
    InOutUk = 'InOutUk'


class StarterDeclaration(Enum):
    PreviouslyReported = 'PreviouslyReported'
    A = 'A'
    B = 'B'
    C = 'C'


class Territory(Enum):
    UnitedKingdom = 'UnitedKingdom'


class WorkingWeek(Enum):
    None_ = 'None'
    Monday = 'Monday'
    Tuesday = 'Tuesday'
    Wednesday = 'Wednesday'
    Thursday = 'Thursday'
    Friday = 'Friday'
    AllWeekDays = 'AllWeekDays'
    Saturday = 'Saturday'
    Sunday = 'Sunday'
    AllDays = 'AllDays'


class Employee2(BaseModel):
    AEAssessmentOverride_1: Optional[AEAssessmentOverride] = Field(
        None,
        alias='AEAssessmentOverride',
        description="The employees' a e assessment override",
        title='AEAssessmentOverride',
    )
    AEAssessmentOverrideDate: Optional[date] = Field(
        None,
        description="The employees' a e assessment override date",
        title='AEAssessmentOverrideDate',
    )
    AEExclusionReasonCode_1: Optional[AEExclusionReasonCode] = Field(
        None,
        alias='AEExclusionReasonCode',
        description="The employees' a e exclusion reason code",
        title='AEExclusionReasonCode',
    )
    AEPostponementDate: Optional[date] = Field(
        None,
        description="The employees' a e postponement date",
        title='AEPostponementDate',
    )
    Address_1: Optional[Address] = Field(
        None, alias='Address', description="The employees' address", title='Address'
    )
    BankAccount_1: Optional[BankAccount] = Field(
        None,
        alias='BankAccount',
        description="The employees' bank account",
        title='BankAccount',
    )
    Code: Optional[str] = Field(None, description="The employees' code", title='Code')
    DateOfBirth: Optional[date] = Field(
        None, description="The employees' date of birth", title='DateOfBirth'
    )
    Deactivated: Optional[bool] = Field(
        None, description="The employees' deactivated", title='Deactivated'
    )
    DirectorshipAppointmentDate: Optional[date] = Field(
        None,
        description="The employees' directorship appointment date",
        title='DirectorshipAppointmentDate',
    )
    EEACitizen: Optional[bool] = Field(
        None, description="The employees' e e a citizen", title='EEACitizen'
    )
    EPM6: Optional[bool] = Field(
        None, description="The employees' e p m6", title='EPM6'
    )
    EffectiveDate: Optional[date] = Field(
        None, description="The employees' effective date", title='EffectiveDate'
    )
    EmployeePartner_1: Optional[EmployeePartner] = Field(
        None,
        alias='EmployeePartner',
        description="The employees' employee partner",
        title='EmployeePartner',
    )
    FirstName: Optional[str] = Field(
        None, description="The employees' the first name", title='FirstName'
    )
    Gender_1: Optional[Gender] = Field(
        None, alias='Gender', description="The employees' gender", title='Gender'
    )
    HoursPerWeek: Optional[float] = Field(
        None, description="The employees' hours per week", title='HoursPerWeek'
    )
    Initials: Optional[str] = Field(
        None, description="The employees' initials", title='Initials'
    )
    IrregularEmployment: Optional[bool] = Field(
        None,
        description="The employees' irregular employment",
        title='IrregularEmployment',
    )
    IsAgencyWorker: Optional[bool] = Field(
        None, description="The employees' is agency worker", title='IsAgencyWorker'
    )
    LastName: Optional[str] = Field(
        None, description="The employees' last name", title='LastName'
    )
    LeaverReason_1: Optional[LeaverReason] = Field(
        None,
        alias='LeaverReason',
        description="The employees' leaver reason",
        title='LeaverReason',
    )
    LeavingDate: Optional[date] = Field(
        None, description="The employees' leaving date", title='LeavingDate'
    )
    MaritalStatus_1: Optional[MaritalStatus] = Field(
        None,
        alias='MaritalStatus',
        description="The employees' marital status",
        title='MaritalStatus',
    )
    MetaData: Optional[Dict[str, Any]] = Field(
        None, description="The employees' meta data", title='MetaData'
    )
    MiddleName: Optional[str] = Field(
        None, description="The employees' middle name", title='MiddleName'
    )
    NextRevisionDate: Optional[date] = Field(
        None, description="The employees' next revision date", title='NextRevisionDate'
    )
    NiNumber: Optional[str] = Field(
        None, description="The employees' ni number", title='NiNumber'
    )
    NicLiability_1: Optional[NicLiability] = Field(
        None,
        alias='NicLiability',
        description="The employees' nic liability",
        title='NicLiability',
    )
    OffPayrollWorker: Optional[bool] = Field(
        None, description="The employees' off payroll worker", title='OffPayrollWorker'
    )
    OnStrike: Optional[bool] = Field(
        None, description="The employees' on strike", title='OnStrike'
    )
    P45IssuedDate: Optional[date] = Field(
        None, description="The employees' p45 issued date", title='P45IssuedDate'
    )
    PassportNumber: Optional[str] = Field(
        None, description="The employees' passport number", title='PassportNumber'
    )
    PaySchedule_1: Optional[PaySchedule] = Field(
        None,
        alias='PaySchedule',
        description="The employees' pay schedule",
        title='PaySchedule',
    )
    PaymentMethod_1: Optional[PaymentMethod] = Field(
        None,
        alias='PaymentMethod',
        description="The employees' payment method",
        title='PaymentMethod',
    )
    PaymentToANonIndividual: Optional[bool] = Field(
        None,
        description="The employees' payment to a non individual",
        title='PaymentToANonIndividual',
    )
    Region_1: Optional[Region] = Field(
        None, alias='Region', description="The employees' region", title='Region'
    )
    Revision: Optional[int] = Field(
        None, description="The employees' revision", title='Revision'
    )
    RuleExclusions_1: Optional[RuleExclusions] = Field(
        None,
        alias='RuleExclusions',
        description="The employees' rule exclusions",
        title='RuleExclusions',
    )
    Seconded_1: Optional[Seconded] = Field(
        None, alias='Seconded', description="The employees' seconded", title='Seconded'
    )
    StartDate: Optional[date] = Field(
        None, description="The employees' start date", title='StartDate'
    )
    StarterDeclaration_1: Optional[StarterDeclaration] = Field(
        None,
        alias='StarterDeclaration',
        description="The employees' starter declaration",
        title='StarterDeclaration',
    )
    Territory_1: Optional[Territory] = Field(
        None,
        alias='Territory',
        description="The employees' territory",
        title='Territory',
    )
    Title: Optional[str] = Field(
        None, description="The employees' title", title='Title'
    )
    VeteranPeriodStartDate: Optional[date] = Field(
        None,
        description="The employees' veteran period start date",
        title='VeteranPeriodStartDate',
    )
    WorkingWeek_1: Optional[WorkingWeek] = Field(
        None,
        alias='WorkingWeek',
        description="The employees' working week",
        title='WorkingWeek',
    )


class Employee1(BaseModel):
    Employee: Optional[Employee2] = Field(None, title='Employee')


class EmployeeSecret1(BaseModel):
    Created: Optional[datetime] = Field(
        None, description="The employee secrets' created", title='Created'
    )
    Name: Optional[str] = Field(
        None, description="The employee secrets' name", title='Name'
    )
    Value: Optional[str] = Field(
        None, description="The employee secrets' value", title='Value'
    )


class EmployeeSecret(BaseModel):
    EmployeeSecret: Optional[EmployeeSecret1] = Field(None, title='EmployeeSecret')


class EmployeeSummary(RootModel[Any]):
    root: Any


class Pension(BaseModel):
    field_href: Optional[str] = Field(
        None, alias='@href', description="The links' href", title='@href'
    )
    field_rel: Optional[str] = Field(
        None, alias='@rel', description="The links' target type", title='@rel'
    )
    field_title: Optional[str] = Field(
        None, alias='@title', description="The links' title", title='@title'
    )


class PrimaryAddress(BaseModel):
    Address1: Optional[str] = Field(
        None, description="The addresss' line 1", title='Address1'
    )
    Address2: Optional[str] = Field(
        None, description="The addresss' line 2", title='Address2'
    )
    Address3: Optional[str] = Field(
        None, description="The addresss' line 3", title='Address3'
    )
    Address4: Optional[str] = Field(
        None, description="The addresss' line 4", title='Address4'
    )
    Country: Optional[str] = Field(
        None, description="The addresss' country", title='Country'
    )
    Postcode: Optional[str] = Field(
        None, description="The addresss' postcode", title='Postcode'
    )


class SecondaryAddress(BaseModel):
    Address1: Optional[str] = Field(
        None, description="The addresss' line 1", title='Address1'
    )
    Address2: Optional[str] = Field(
        None, description="The addresss' line 2", title='Address2'
    )
    Address3: Optional[str] = Field(
        None, description="The addresss' line 3", title='Address3'
    )
    Address4: Optional[str] = Field(
        None, description="The addresss' line 4", title='Address4'
    )
    Country: Optional[str] = Field(
        None, description="The addresss' country", title='Country'
    )
    Postcode: Optional[str] = Field(
        None, description="The addresss' postcode", title='Postcode'
    )


class AutoEnrolment(BaseModel):
    Pension_1: Optional[Pension] = Field(
        None,
        alias='Pension',
        description="The employer auto enrolments' pension",
        title='Pension',
    )
    PostponementDate: Optional[date] = Field(
        None,
        description="The employer auto enrolments' postponement date",
        title='PostponementDate',
    )
    PrimaryAddress_1: Optional[PrimaryAddress] = Field(
        None,
        alias='PrimaryAddress',
        description="The employer auto enrolments' primary address",
        title='PrimaryAddress',
    )
    PrimaryEmail: Optional[str] = Field(
        None,
        description="The employer auto enrolments' primary email",
        title='PrimaryEmail',
    )
    PrimaryFirstName: Optional[str] = Field(
        None,
        description="The employer auto enrolments' primary first name",
        title='PrimaryFirstName',
    )
    PrimaryJobTitle: Optional[str] = Field(
        None,
        description="The employer auto enrolments' primary job title",
        title='PrimaryJobTitle',
    )
    PrimaryLastName: Optional[str] = Field(
        None,
        description="The employer auto enrolments' primary last name",
        title='PrimaryLastName',
    )
    PrimaryTelephone: Optional[str] = Field(
        None,
        description="The employer auto enrolments' primary telephone",
        title='PrimaryTelephone',
    )
    ReEnrolmentDayOffset: Optional[int] = Field(
        None,
        description="The employer auto enrolments' re enrolment day offset",
        title='ReEnrolmentDayOffset',
    )
    ReEnrolmentMonthOffset: Optional[int] = Field(
        None,
        description="The employer auto enrolments' re enrolment month offset",
        title='ReEnrolmentMonthOffset',
    )
    RecentOptOutReEnrolmentExcluded: Optional[bool] = Field(
        None,
        description="The employer auto enrolments' recent opt out re enrolment excluded",
        title='RecentOptOutReEnrolmentExcluded',
    )
    SecondaryAddress_1: Optional[SecondaryAddress] = Field(
        None,
        alias='SecondaryAddress',
        description="The employer auto enrolments' secondary address",
        title='SecondaryAddress',
    )
    SecondaryEmail: Optional[str] = Field(
        None,
        description="The employer auto enrolments' secondary email",
        title='SecondaryEmail',
    )
    SecondaryFirstName: Optional[str] = Field(
        None,
        description="The employer auto enrolments' secondary first name",
        title='SecondaryFirstName',
    )
    SecondaryJobTitle: Optional[str] = Field(
        None,
        description="The employer auto enrolments' secondary job title",
        title='SecondaryJobTitle',
    )
    SecondaryLastName: Optional[str] = Field(
        None,
        description="The employer auto enrolments' secondary last name",
        title='SecondaryLastName',
    )
    SecondaryTelephone: Optional[str] = Field(
        None,
        description="The employer auto enrolments' secondary telephone",
        title='SecondaryTelephone',
    )
    StagingDate: Optional[date] = Field(
        None,
        description="The employer auto enrolments' staging date",
        title='StagingDate',
    )


class Sender(Enum):
    Employer = 'Employer'
    Individual = 'Individual'
    Company = 'Company'
    Agent = 'Agent'
    Bureau = 'Bureau'
    Partnership = 'Partnership'
    Trust = 'Trust'
    Government = 'Government'
    ActingInCapacity = 'ActingInCapacity'
    Other = 'Other'


class StateAidSector(Enum):
    Agriculture = 'Agriculture'
    FisheriesAquaculture = 'FisheriesAquaculture'
    RoadTransport = 'RoadTransport'
    Industrial = 'Industrial'
    NotApplicable = 'NotApplicable'


class HmrcSettings(BaseModel):
    AccountingOfficeRef: Optional[str] = Field(
        None,
        description="The hmrc settingss' accounting office ref",
        title='AccountingOfficeRef',
    )
    COTAXRef: Optional[str] = Field(
        None, description="The hmrc settingss' c o t a x ref", title='COTAXRef'
    )
    ContactEmail: Optional[str] = Field(
        None, description="The hmrc settingss' contact email", title='ContactEmail'
    )
    ContactFax: Optional[str] = Field(
        None, description="The hmrc settingss' contact fax", title='ContactFax'
    )
    ContactFirstName: Optional[str] = Field(
        None,
        description="The hmrc settingss' contact first name",
        title='ContactFirstName',
    )
    ContactLastName: Optional[str] = Field(
        None,
        description="The hmrc settingss' contact last name",
        title='ContactLastName',
    )
    ContactTelephone: Optional[str] = Field(
        None,
        description="The hmrc settingss' contact telephone",
        title='ContactTelephone',
    )
    EmploymentAllowanceOverride: Optional[float] = Field(
        None,
        description="The hmrc settingss' employment allowance override",
        title='EmploymentAllowanceOverride',
    )
    Password: Optional[SecretStr] = Field(
        None, description="The hmrc settingss' password", title='Password'
    )
    SAUTR: Optional[str] = Field(
        None, description="The hmrc settingss' s a u t r", title='SAUTR'
    )
    Sender_1: Optional[Sender] = Field(
        None, alias='Sender', description="The hmrc settingss' sender", title='Sender'
    )
    SenderId: Optional[str] = Field(
        None, description="The hmrc settingss' sender id", title='SenderId'
    )
    StateAidSector_1: Optional[StateAidSector] = Field(
        None,
        alias='StateAidSector',
        description="The hmrc settingss' state aid sector",
        title='StateAidSector',
    )
    TaxOfficeNumber: Optional[str] = Field(
        None,
        description="The hmrc settingss' tax office number",
        title='TaxOfficeNumber',
    )
    TaxOfficeReference: Optional[str] = Field(
        None,
        description="The hmrc settingss' tax office reference",
        title='TaxOfficeReference',
    )


class Employer3(BaseModel):
    Address_1: Optional[Address] = Field(
        None, alias='Address', description="The employers' address", title='Address'
    )
    ApprenticeshipLevyAllowance: Optional[float] = Field(
        None,
        description="The employers' apprenticeship levy allowance",
        title='ApprenticeshipLevyAllowance',
    )
    AutoEnrolment_1: Optional[AutoEnrolment] = Field(
        None,
        alias='AutoEnrolment',
        description="The employers' auto enrolment",
        title='AutoEnrolment',
    )
    BacsServiceUserNumber: Optional[str] = Field(
        None,
        description="The employers' bacs service user number",
        title='BacsServiceUserNumber',
    )
    BankAccount_1: Optional[BankAccount] = Field(
        None,
        alias='BankAccount',
        description="The employers' bank account",
        title='BankAccount',
    )
    CalculateApprenticeshipLevy: Optional[bool] = Field(
        None,
        description="The employers' calculate apprenticeship levy",
        title='CalculateApprenticeshipLevy',
    )
    ClaimEmploymentAllowance: Optional[bool] = Field(
        None,
        description="The employers' claim employment allowance",
        title='ClaimEmploymentAllowance',
    )
    ClaimSmallEmployerRelief: Optional[bool] = Field(
        None,
        description="The employers' claim small employer relief",
        title='ClaimSmallEmployerRelief',
    )
    EffectiveDate: Optional[date] = Field(
        None, description="The employers' effective date", title='EffectiveDate'
    )
    HmrcSettings_1: Optional[HmrcSettings] = Field(
        None,
        alias='HmrcSettings',
        description="The employers' hmrc settings",
        title='HmrcSettings',
    )
    MetaData: Optional[Dict[str, Any]] = Field(
        None, description="The employers' meta data", title='MetaData'
    )
    Name: Optional[str] = Field(None, description="The employers' name", title='Name')
    NextRevisionDate: Optional[date] = Field(
        None, description="The employers' next revision date", title='NextRevisionDate'
    )
    Region_1: Optional[Region] = Field(
        None, alias='Region', description="The employers' region", title='Region'
    )
    Revision: Optional[int] = Field(
        None, description="The employers' revision", title='Revision'
    )
    RuleExclusions_1: Optional[RuleExclusions] = Field(
        None,
        alias='RuleExclusions',
        description="The employers' rule exclusions",
        title='RuleExclusions',
    )
    Territory_1: Optional[Territory] = Field(
        None,
        alias='Territory',
        description="The employers' territory",
        title='Territory',
    )


class Employer2(BaseModel):
    Employer: Optional[Employer3] = Field(None, title='Employer')


class EmployerSecret1(BaseModel):
    Created: Optional[datetime] = Field(
        None, description="The employer secrets' created", title='Created'
    )
    Name: Optional[str] = Field(
        None, description="The employer secrets' name", title='Name'
    )
    Value: Optional[str] = Field(
        None, description="The employer secrets' value", title='Value'
    )


class EmployerSecret(BaseModel):
    EmployerSecret: Optional[EmployerSecret1] = Field(None, title='EmployerSecret')


class EmployerSummary(RootModel[Any]):
    root: Any


class ErrorCategory(Enum):
    General = 'General'
    NotFound = 'NotFound'
    NotAuthorised = 'NotAuthorised'
    ValidationFailure = 'ValidationFailure'


class Errors(BaseModel):
    Error: Optional[List[str]] = None


class ErrorModel1(BaseModel):
    Description: Optional[str] = Field(
        None, description="The error models' description", title='Description'
    )
    ErrorCategory_1: Optional[ErrorCategory] = Field(
        None,
        alias='ErrorCategory',
        description="The error models' error category",
        title='ErrorCategory',
    )
    Errors_1: Optional[Errors] = Field(
        None, alias='Errors', description="The error models' errors", title='Errors'
    )


class ErrorModel(BaseModel):
    ErrorModel: Optional[ErrorModel1] = Field(None, title='ErrorModel')


class HealthCheck1(BaseModel):
    Info: Optional[str] = Field(
        None, description="The health checks' info", title='Info'
    )
    Version: Optional[str] = Field(
        None, description="The health checks' version", title='Version'
    )


class HealthCheck(BaseModel):
    HealthCheck: Optional[HealthCheck1] = Field(None, title='HealthCheck')


class AccrualPayCodes(BaseModel):
    PayCode: Optional[List[str]] = None


class HolidayScheme1(BaseModel):
    AccrualPayCodes_1: Optional[AccrualPayCodes] = Field(
        None,
        alias='AccrualPayCodes',
        description="The holiday schemes' accrual pay codes",
        title='AccrualPayCodes',
    )
    AllowExceedAnnualEntitlement: Optional[bool] = Field(
        None,
        description="The holiday schemes' allow exceed annual entitlement",
        title='AllowExceedAnnualEntitlement',
    )
    AllowNegativeBalance: Optional[bool] = Field(
        None,
        description="The holiday schemes' allow negative balance",
        title='AllowNegativeBalance',
    )
    AnnualEntitlementWeeks: Optional[float] = Field(
        None,
        description="The holiday schemes' annual entitlement weeks",
        title='AnnualEntitlementWeeks',
    )
    BankHolidayInclusive: Optional[bool] = Field(
        None,
        description="The holiday schemes' bank holiday inclusive",
        title='BankHolidayInclusive',
    )
    Code: Optional[str] = Field(
        None, description="The holiday schemes' code", title='Code'
    )
    EffectiveDate: Optional[date] = Field(
        None, description="The holiday schemes' effective date", title='EffectiveDate'
    )
    MaxCarryOverDays: Optional[float] = Field(
        None,
        description="The holiday schemes' max carry over days",
        title='MaxCarryOverDays',
    )
    NextRevisionDate: Optional[date] = Field(
        None,
        description="The holiday schemes' next revision date",
        title='NextRevisionDate',
    )
    OffsetPayment: Optional[bool] = Field(
        None, description="The holiday schemes' offset payment", title='OffsetPayment'
    )
    Revision: Optional[int] = Field(
        None, description="The holiday schemes' revision", title='Revision'
    )
    SchemeCeasedDate: Optional[date] = Field(
        None,
        description="The holiday schemes' scheme ceased date",
        title='SchemeCeasedDate',
    )
    SchemeKey: Optional[str] = Field(
        None, description="The holiday schemes' scheme key", title='SchemeKey'
    )
    SchemeName: Optional[str] = Field(
        None, description="The holiday schemes' scheme name", title='SchemeName'
    )
    YearStartDay: Optional[int] = Field(
        None, description="The holiday schemes' year start day", title='YearStartDay'
    )
    YearStartMonth: Optional[int] = Field(
        None,
        description="The holiday schemes' year start month",
        title='YearStartMonth',
    )


class HolidayScheme(BaseModel):
    HolidayScheme: Optional[HolidayScheme1] = Field(None, title='HolidayScheme')


class JobStatus(Enum):
    New = 'New'
    Pending = 'Pending'
    InProgress = 'InProgress'
    Success = 'Success'
    Failed = 'Failed'
    OnHold = 'OnHold'


class JobInfo1(BaseModel):
    Created: Optional[datetime] = Field(
        None, description="The job infos' created", title='Created'
    )
    EmployerKey: Optional[str] = Field(
        None, description="The job infos' employer key", title='EmployerKey'
    )
    Errors_1: Optional[Errors] = Field(
        None, alias='Errors', description="The job infos' errors", title='Errors'
    )
    HoldingDate: Optional[datetime] = Field(
        None, description="The job infos' holding date", title='HoldingDate'
    )
    JobId: Optional[str] = Field(
        None, description="The job infos' job id", title='JobId'
    )
    JobStatus_1: Optional[JobStatus] = Field(
        None,
        alias='JobStatus',
        description="The job infos' job status",
        title='JobStatus',
    )
    JobType: Optional[str] = Field(
        None, description="The job infos' job type", title='JobType'
    )
    LastUpdated: Optional[datetime] = Field(
        None, description="The job infos' last updated", title='LastUpdated'
    )
    Progress: Optional[float] = Field(
        None, description="The job infos' progress", title='Progress'
    )


class JobInfo(BaseModel):
    JobInfo: Optional[JobInfo1] = Field(None, title='JobInfo')


class JournalExpressionDataTable(RootModel[Any]):
    root: Any


class AccountingType(Enum):
    Credit = 'Credit'
    Debit = 'Debit'


class JournalInstruction1(BaseModel):
    AccountingType_1: Optional[AccountingType] = Field(
        None,
        alias='AccountingType',
        description="The journal instructions' accounting type",
        title='AccountingType',
    )
    Description: Optional[str] = Field(
        None, description="The journal instructions' description", title='Description'
    )
    EndDate: Optional[date] = Field(
        None, description="The journal instructions' end date", title='EndDate'
    )
    Expression: Optional[str] = Field(
        None, description="The journal instructions' expression", title='Expression'
    )
    JournalLineTag: Optional[str] = Field(
        None,
        description="The journal instructions' journal line tag",
        title='JournalLineTag',
    )
    LedgerTarget: Optional[str] = Field(
        None,
        description="The journal instructions' ledger target",
        title='LedgerTarget',
    )
    NomCode: Optional[str] = Field(
        None, description="The journal instructions' nom code", title='NomCode'
    )
    StartDate: Optional[date] = Field(
        None, description="The journal instructions' start date", title='StartDate'
    )
    SubNomCode: Optional[str] = Field(
        None, description="The journal instructions' sub nom code", title='SubNomCode'
    )


class JournalInstruction(BaseModel):
    JournalInstruction: Optional[JournalInstruction1] = Field(
        None, title='JournalInstruction'
    )


class Employee3(BaseModel):
    field_href: Optional[str] = Field(
        None, alias='@href', description="The links' href", title='@href'
    )
    field_rel: Optional[str] = Field(
        None, alias='@rel', description="The links' target type", title='@rel'
    )
    field_title: Optional[str] = Field(
        None, alias='@title', description="The links' title", title='@title'
    )


class PayFrequency2(Enum):
    Weekly = 'Weekly'
    Monthly = 'Monthly'
    TwoWeekly = 'TwoWeekly'
    FourWeekly = 'FourWeekly'
    Yearly = 'Yearly'


class SubContractor(BaseModel):
    field_href: Optional[str] = Field(
        None, alias='@href', description="The links' href", title='@href'
    )
    field_rel: Optional[str] = Field(
        None, alias='@rel', description="The links' target type", title='@rel'
    )
    field_title: Optional[str] = Field(
        None, alias='@title', description="The links' title", title='@title'
    )


class JournalLine1(BaseModel):
    Credit: Optional[float] = Field(
        None, description="The journal lines' credit", title='Credit'
    )
    Debit: Optional[float] = Field(
        None, description="The journal lines' debit", title='Debit'
    )
    Description: Optional[str] = Field(
        None, description="The journal lines' description", title='Description'
    )
    Employee: Optional[Employee3] = Field(
        None, description="The journal lines' employee", title='Employee'
    )
    Generated: Optional[datetime] = Field(
        None, description="The journal lines' generated", title='Generated'
    )
    Grouping: Optional[str] = Field(
        None, description="The journal lines' grouping", title='Grouping'
    )
    LedgerTarget: Optional[str] = Field(
        None, description="The journal lines' ledger target", title='LedgerTarget'
    )
    NomCode: Optional[str] = Field(
        None, description="The journal lines' nom code", title='NomCode'
    )
    PayFrequency: Optional[PayFrequency2] = Field(
        None, description="The journal lines' pay frequency", title='PayFrequency'
    )
    PayRun_1: Optional[PayRun] = Field(
        None, alias='PayRun', description="The journal lines' pay run", title='PayRun'
    )
    SubContractor_1: Optional[SubContractor] = Field(
        None,
        alias='SubContractor',
        description="The journal lines' sub contractor",
        title='SubContractor',
    )
    SubNomCode: Optional[str] = Field(
        None, description="The journal lines' sub nom code", title='SubNomCode'
    )
    TaxPeriod: Optional[int] = Field(
        None, description="The journal lines' tax period", title='TaxPeriod'
    )
    TaxYear: Optional[int] = Field(
        None, description="The journal lines' tax year", title='TaxYear'
    )


class JournalLine(BaseModel):
    JournalLine: Optional[JournalLine1] = Field(None, title='JournalLine')


class Link1(BaseModel):
    field_href: Optional[str] = Field(
        None, alias='@href', description="The links' href", title='@href'
    )
    field_rel: Optional[str] = Field(
        None, alias='@rel', description="The links' target type", title='@rel'
    )
    field_title: Optional[str] = Field(
        None, alias='@title', description="The links' title", title='@title'
    )


class Link(BaseModel):
    Link: Optional[Link1] = Field(None, title='Link')


class LinkItem(BaseModel):
    field_href: Optional[str] = Field(
        None, alias='@href', description="The links' href", title='@href'
    )
    field_rel: Optional[str] = Field(
        None, alias='@rel', description="The links' target type", title='@rel'
    )
    field_title: Optional[str] = Field(
        None, alias='@title', description="The links' title", title='@title'
    )


class Links(BaseModel):
    Link: Optional[List[LinkItem]] = None


class LinkCollection1(BaseModel):
    Links_1: Optional[Links] = Field(
        None, alias='Links', description="The link collections' links", title='Link'
    )


class LinkCollection(BaseModel):
    LinkCollection: Optional[LinkCollection1] = Field(None, title='LinkCollection')


class NominalCode2(BaseModel):
    Description: Optional[str] = Field(
        None, description="The nominal codes' description", title='Description'
    )
    Key: Optional[str] = Field(None, description="The nominal codes' key", title='Key')


class NominalCode1(BaseModel):
    NominalCode: Optional[NominalCode2] = Field(None, title='NominalCode')


class NominalCode3(BaseModel):
    field_href: Optional[str] = Field(
        None, alias='@href', description="The links' href", title='@href'
    )
    field_rel: Optional[str] = Field(
        None, alias='@rel', description="The links' target type", title='@rel'
    )
    field_title: Optional[str] = Field(
        None, alias='@title', description="The links' title", title='@title'
    )


class Type(Enum):
    NotSet = 'NotSet'
    Payment = 'Payment'
    Deduction = 'Deduction'


class PayCode1(BaseModel):
    Benefit: Optional[bool] = Field(
        None, description="The pay codes' benefit", title='Benefit'
    )
    Code: Optional[str] = Field(None, description="The pay codes' code", title='Code')
    Description: Optional[str] = Field(
        None, description="The pay codes' description", title='Description'
    )
    EffectiveDate: Optional[date] = Field(
        None, description="The pay codes' effective date", title='EffectiveDate'
    )
    MetaData: Optional[Dict[str, Any]] = Field(
        None, description="The pay codes' meta data", title='MetaData'
    )
    NextRevisionDate: Optional[date] = Field(
        None, description="The pay codes' next revision date", title='NextRevisionDate'
    )
    Niable: Optional[bool] = Field(
        None, description="The pay codes' niable", title='Niable'
    )
    NominalCode: Optional[NominalCode3] = Field(
        None, description="The pay codes' nominal code", title='NominalCode'
    )
    NonArrestable: Optional[bool] = Field(
        None, description="The pay codes' non arrestable", title='NonArrestable'
    )
    Notional: Optional[bool] = Field(
        None, description="The pay codes' notional", title='Notional'
    )
    Readonly: Optional[bool] = Field(
        None, description="The pay codes' readonly", title='Readonly'
    )
    Region_1: Optional[Region] = Field(
        None, alias='Region', description="The pay codes' region", title='Region'
    )
    Revision: Optional[int] = Field(
        None, description="The pay codes' revision", title='Revision'
    )
    Taxable: Optional[bool] = Field(
        None, description="The pay codes' taxable", title='Taxable'
    )
    Territory_1: Optional[Territory] = Field(
        None,
        alias='Territory',
        description="The pay codes' territory",
        title='Territory',
    )
    Type_1: Optional[Type] = Field(
        None, alias='Type', description="The pay codes' type", title='Type'
    )


class PayCode(BaseModel):
    PayCode: Optional[PayCode1] = Field(None, title='PayCode')


class PayInstruction1(BaseModel):
    Description: Optional[str] = Field(
        None, description="The pay instructions' description", title='Description'
    )
    EndDate: Optional[date] = Field(
        None, description="The pay instructions' end date", title='EndDate'
    )
    PayLineTag: Optional[str] = Field(
        None, description="The pay instructions' pay line tag", title='PayLineTag'
    )
    StartDate: Optional[date] = Field(
        None, description="The pay instructions' start date", title='StartDate'
    )


class PayInstruction(BaseModel):
    PayInstruction: Optional[PayInstruction1] = Field(None, title='PayInstruction')


class PayCodeType(Enum):
    NotSet = 'NotSet'
    Payment = 'Payment'
    Deduction = 'Deduction'


class PayLine1(BaseModel):
    Calculator: Optional[str] = Field(
        None, description="The pay lines' calculator", title='Calculator'
    )
    Description: Optional[str] = Field(
        None, description="The pay lines' description", title='Description'
    )
    Generated: Optional[datetime] = Field(
        None, description="The pay lines' generated", title='Generated'
    )
    PayCode: Optional[str] = Field(
        None, description="The pay lines' pay code", title='PayCode'
    )
    PayCodeType_1: Optional[PayCodeType] = Field(
        None,
        alias='PayCodeType',
        description="The pay lines' pay code type",
        title='PayCodeType',
    )
    PayRunSequence: Optional[int] = Field(
        None, description="The pay lines' pay run sequence", title='PayRunSequence'
    )
    PaymentDate: Optional[date] = Field(
        None, description="The pay lines' payment date", title='PaymentDate'
    )
    TaxPeriod: Optional[int] = Field(
        None, description="The pay lines' tax period", title='TaxPeriod'
    )
    TaxYear: Optional[int] = Field(
        None, description="The pay lines' tax year", title='TaxYear'
    )
    Value: Optional[float] = Field(
        None, description="The pay lines' value", title='Value'
    )


class PayLine(BaseModel):
    PayLine: Optional[PayLine1] = Field(None, title='PayLine')


class ProceedingPayRun(BaseModel):
    field_href: Optional[str] = Field(
        None, alias='@href', description="The links' href", title='@href'
    )
    field_rel: Optional[str] = Field(
        None, alias='@rel', description="The links' target type", title='@rel'
    )
    field_title: Optional[str] = Field(
        None, alias='@title', description="The links' title", title='@title'
    )


class PayRun3(BaseModel):
    Executed: Optional[datetime] = Field(
        None, description="The pay runs' executed", title='Executed'
    )
    IsSupplementary: Optional[bool] = Field(
        None, description="The pay runs' is supplementary", title='IsSupplementary'
    )
    PayFrequency: Optional[PayFrequency2] = Field(
        None, description="The pay runs' pay frequency", title='PayFrequency'
    )
    PaySchedule_1: Optional[PaySchedule] = Field(
        None,
        alias='PaySchedule',
        description="The pay runs' pay schedule",
        title='PaySchedule',
    )
    PaymentDate: Optional[date] = Field(
        None, description="The pay runs' payment date", title='PaymentDate'
    )
    PeriodEnd: Optional[date] = Field(
        None, description="The pay runs' period end", title='PeriodEnd'
    )
    PeriodStart: Optional[date] = Field(
        None, description="The pay runs' period start", title='PeriodStart'
    )
    ProceedingPayRun_1: Optional[ProceedingPayRun] = Field(
        None,
        alias='ProceedingPayRun',
        description="The pay runs' proceeding pay run",
        title='ProceedingPayRun',
    )
    Sequence: Optional[int] = Field(
        None, description="The pay runs' sequence", title='Sequence'
    )
    TaxPeriod: Optional[int] = Field(
        None, description="The pay runs' tax period", title='TaxPeriod'
    )
    TaxYear: Optional[int] = Field(
        None, description="The pay runs' tax year", title='TaxYear'
    )


class PayRun2(BaseModel):
    PayRun: Optional[PayRun3] = Field(None, title='PayRun')


class EmployeeItem(BaseModel):
    field_href: Optional[str] = Field(
        None, alias='@href', description="The links' href", title='@href'
    )
    field_rel: Optional[str] = Field(
        None, alias='@rel', description="The links' target type", title='@rel'
    )
    field_title: Optional[str] = Field(
        None, alias='@title', description="The links' title", title='@title'
    )


class Employees(BaseModel):
    Employee: Optional[List[EmployeeItem]] = None


class PayRunJobInstruction1(BaseModel):
    Employees_1: Optional[Employees] = Field(
        None,
        alias='Employees',
        description="The pay run job instructions' employees",
        title='Employee',
    )
    EndDate: Optional[date] = Field(
        None, description="The pay run job instructions' end date", title='EndDate'
    )
    HoldingDate: Optional[datetime] = Field(
        None,
        description="The pay run job instructions' holding date",
        title='HoldingDate',
    )
    IsSupplementary: Optional[bool] = Field(
        None,
        description="The pay run job instructions' is supplementary",
        title='IsSupplementary',
    )
    PaySchedule_1: Optional[PaySchedule] = Field(
        None,
        alias='PaySchedule',
        description="The pay run job instructions' pay schedule",
        title='PaySchedule',
    )
    PaymentDate: Optional[date] = Field(
        None,
        description="The pay run job instructions' payment date",
        title='PaymentDate',
    )
    StartDate: Optional[date] = Field(
        None, description="The pay run job instructions' start date", title='StartDate'
    )


class PayRunJobInstruction(BaseModel):
    PayRunJobInstruction: Optional[PayRunJobInstruction1] = Field(
        None, title='PayRunJobInstruction'
    )


class PaySchedule4(BaseModel):
    MetaData: Optional[Dict[str, Any]] = Field(
        None, description="The pay schedules' meta data", title='MetaData'
    )
    Name: Optional[str] = Field(
        None, description="The pay schedules' name", title='Name'
    )
    PayFrequency: Optional[PayFrequency2] = Field(
        None, description="The pay schedules' pay frequency", title='PayFrequency'
    )


class PaySchedule3(BaseModel):
    PaySchedule: Optional[PaySchedule4] = Field(None, title='PaySchedule')


class Certification(Enum):
    NotSet = 'NotSet'
    Set1 = 'Set1'
    Set2 = 'Set2'
    Set3 = 'Set3'


class PensionablePayCodes(BaseModel):
    PayCode: Optional[List[str]] = None


class ProRataMethod(Enum):
    NotSet = 'NotSet'
    Annual260Days = 'Annual260Days'
    Annual365Days = 'Annual365Days'
    AnnualQualifyingDays = 'AnnualQualifyingDays'
    DaysPerCalendarMonth = 'DaysPerCalendarMonth'
    DaysPerTaxPeriod = 'DaysPerTaxPeriod'
    WorkingDaysPerCalendarMonth = 'WorkingDaysPerCalendarMonth'
    WeekDaysPerCalendarMonth = 'WeekDaysPerCalendarMonth'


class QualifyingPayCodes(BaseModel):
    PayCode: Optional[List[str]] = None


class RasRoundingOverride(Enum):
    NotSet = 'NotSet'
    PennyUp = 'PennyUp'
    PennyDown = 'PennyDown'
    Bankers = 'Bankers'
    FiveUp = 'FiveUp'
    FiveDown = 'FiveDown'
    Floor = 'Floor'
    Ceiling = 'Ceiling'


class RoundingOption(Enum):
    NotSet = 'NotSet'
    PennyUp = 'PennyUp'
    PennyDown = 'PennyDown'
    Bankers = 'Bankers'
    FiveUp = 'FiveUp'
    FiveDown = 'FiveDown'
    Floor = 'Floor'
    Ceiling = 'Ceiling'


class TaxationMethod(Enum):
    NotSet = 'NotSet'
    NetBased = 'NetBased'
    ReliefAtSource = 'ReliefAtSource'
    TaxReliefExcluded = 'TaxReliefExcluded'


class Pension2(BaseModel):
    AECompatible: Optional[bool] = Field(
        None, description="The pensions' a e compatible", title='AECompatible'
    )
    Certification_1: Optional[Certification] = Field(
        None,
        alias='Certification',
        description="The pensions' certification",
        title='Certification',
    )
    Code: Optional[str] = Field(None, description="The pensions' code", title='Code')
    ContributionDeductionDay: Optional[int] = Field(
        None,
        description="The pensions' contribution deduction day",
        title='ContributionDeductionDay',
    )
    EffectiveDate: Optional[date] = Field(
        None, description="The pensions' effective date", title='EffectiveDate'
    )
    EmployeeContributionCash: Optional[float] = Field(
        None,
        description="The pensions' employee contribution cash",
        title='EmployeeContributionCash',
    )
    EmployeeContributionPercent: Optional[float] = Field(
        None,
        description="The pensions' employee contribution percent",
        title='EmployeeContributionPercent',
    )
    EmployerContributionCash: Optional[float] = Field(
        None,
        description="The pensions' employer contribution cash",
        title='EmployerContributionCash',
    )
    EmployerContributionPercent: Optional[float] = Field(
        None,
        description="The pensions' employer contribution percent",
        title='EmployerContributionPercent',
    )
    EmployerNiSaving: Optional[bool] = Field(
        None, description="The pensions' employer ni saving", title='EmployerNiSaving'
    )
    EmployerNiSavingPercentage: Optional[float] = Field(
        None,
        description="The pensions' employer ni saving percentage",
        title='EmployerNiSavingPercentage',
    )
    Group: Optional[str] = Field(None, description="The pensions' group", title='Group')
    LowerThreshold: Optional[float] = Field(
        None, description="The pensions' lower threshold", title='LowerThreshold'
    )
    MetaData: Optional[Dict[str, Any]] = Field(
        None, description="The pensions' meta data", title='MetaData'
    )
    NextRevisionDate: Optional[date] = Field(
        None, description="The pensions' next revision date", title='NextRevisionDate'
    )
    PensionablePayCodes_1: Optional[PensionablePayCodes] = Field(
        None,
        alias='PensionablePayCodes',
        description="The pensions' pensionable pay codes",
        title='PensionablePayCodes',
    )
    ProRataMethod_1: Optional[ProRataMethod] = Field(
        None,
        alias='ProRataMethod',
        description="The pensions' pro rata method",
        title='ProRataMethod',
    )
    ProviderEmployerRef: Optional[str] = Field(
        None,
        description="The pensions' provider employer ref",
        title='ProviderEmployerRef',
    )
    ProviderName: Optional[str] = Field(
        None, description="The pensions' provider name", title='ProviderName'
    )
    QualifyingPayCodes_1: Optional[QualifyingPayCodes] = Field(
        None,
        alias='QualifyingPayCodes',
        description="The pensions' qualifying pay codes",
        title='QualifyingPayCodes',
    )
    RasRoundingOverride_1: Optional[RasRoundingOverride] = Field(
        None,
        alias='RasRoundingOverride',
        description="The pensions' ras rounding override",
        title='RasRoundingOverride',
    )
    Revision: Optional[int] = Field(
        None, description="The pensions' revision", title='Revision'
    )
    RoundingOption_1: Optional[RoundingOption] = Field(
        None,
        alias='RoundingOption',
        description="The pensions' rounding option",
        title='RoundingOption',
    )
    SalarySacrifice: Optional[bool] = Field(
        None, description="The pensions' salary sacrifice", title='SalarySacrifice'
    )
    SchemeName: Optional[str] = Field(
        None, description="The pensions' scheme name", title='SchemeName'
    )
    SubGroup: Optional[str] = Field(
        None, description="The pensions' sub group", title='SubGroup'
    )
    TaxationMethod_1: Optional[TaxationMethod] = Field(
        None,
        alias='TaxationMethod',
        description="The pensions' taxation method",
        title='TaxationMethod',
    )
    UpperThreshold: Optional[float] = Field(
        None, description="The pensions' upper threshold", title='UpperThreshold'
    )
    UseAEThresholds: Optional[bool] = Field(
        None, description="The pensions' use a e thresholds", title='UseAEThresholds'
    )


class Pension1(BaseModel):
    Pension: Optional[Pension2] = Field(None, title='Pension')


class Policy(Enum):
    Allow = 'Allow'
    Deny = 'Deny'


class Verbs(Enum):
    Read = 'Read'
    Write = 'Write'
    Delete = 'Delete'
    All = 'All'


class Permission1(BaseModel):
    Description: Optional[str] = Field(
        None, description="The permissions' description", title='Description'
    )
    Expression: Optional[str] = Field(
        None, description="The permissions' expression", title='Expression'
    )
    Name: Optional[str] = Field(None, description="The permissions' name", title='Name')
    Policy_1: Optional[Policy] = Field(
        None, alias='Policy', description="The permissions' policy", title='Policy'
    )
    Verbs_1: Optional[Verbs] = Field(
        None, alias='Verbs', description="The permissions' verbs", title='Verbs'
    )


class Permission(BaseModel):
    Permission: Optional[Permission1] = Field(None, title='Permission')


class ConditionItem(BaseModel):
    field_ValueA: Optional[str] = Field(
        None,
        alias='@ValueA',
        description="The compare condition bases' value a",
        title='@ValueA',
    )
    field_ValueB: Optional[str] = Field(
        None,
        alias='@ValueB',
        description="The compare condition bases' value b",
        title='@ValueB',
    )


class FilterItem(BaseModel):
    field_IsOr: Optional[bool] = Field(
        None, alias='@IsOr', description="The filter bases' is or", title='@IsOr'
    )
    field_Property: Optional[str] = Field(
        None,
        alias='@Property',
        description="The filter bases' property",
        title='@Property',
    )
    field_Value: Optional[str] = Field(
        None, alias='@Value', description="The filter bases' value", title='@Value'
    )


class OrderItem(BaseModel):
    field_Property: Optional[str] = Field(
        None,
        alias='@Property',
        description="The order by bases' property",
        title='@Property',
    )


class FieldOutput(Enum):
    Element = 'Element'
    Attribute = 'Attribute'
    Variable = 'Variable'
    VariableSum = 'VariableSum'
    VariableAppend = 'VariableAppend'
    VariablePrepend = 'VariablePrepend'
    ElementDatePart = 'ElementDatePart'
    InnerText = 'InnerText'


class OutputItem(BaseModel):
    field_MaxLength: Optional[str] = Field(
        None,
        alias='@MaxLength',
        description="The output bases' max length",
        title='@MaxLength',
    )
    field_Output: Optional[FieldOutput] = Field(
        None, alias='@Output', description="The output bases' output", title='@Output'
    )


class GroupItem(BaseModel):
    field_GroupName: Optional[str] = Field(
        None,
        alias='@GroupName',
        description="The entity groups' group name",
        title='@GroupName',
    )
    field_ItemName: Optional[str] = Field(
        None,
        alias='@ItemName',
        description="The entity groups' item name",
        title='@ItemName',
    )
    field_LoopExpression: Optional[str] = Field(
        None,
        alias='@LoopExpression',
        description="The entity groups' loop expression",
        title='@LoopExpression',
    )
    field_Predicate: Optional[str] = Field(
        None,
        alias='@Predicate',
        description="The entity groups' predicate",
        title='@Predicate',
    )
    field_Selector: Optional[str] = Field(
        None,
        alias='@Selector',
        description="The entity groups' selector",
        title='@Selector',
    )
    field_UniqueKeyVariable: Optional[str] = Field(
        None,
        alias='@UniqueKeyVariable',
        description="The entity groups' unique key variable",
        title='@UniqueKeyVariable',
    )
    Condition: Optional[List[ConditionItem]] = Field(
        None, description="The entity groups' conditions", title='Condition'
    )
    Filter: Optional[List[FilterItem]] = Field(
        None, description="The entity groups' filters", title='Filter'
    )
    Order: Optional[List[OrderItem]] = Field(
        None, description="The entity groups' ordering", title='Order'
    )
    Output: Optional[List[OutputItem]] = Field(
        None, description="The entity groups' outputs", title='Output'
    )


class Groups(BaseModel):
    Group: Optional[List[GroupItem]] = None


class VariableItem(BaseModel):
    field_Name: Optional[str] = Field(
        None, alias='@Name', description="The name value pairs' name", title='@Name'
    )
    field_Value: Optional[str] = Field(
        None, alias='@Value', description="The name value pairs' value", title='@Value'
    )


class Variables(BaseModel):
    Variable: Optional[List[VariableItem]] = None


class Query1(BaseModel):
    Encoding: Optional[str] = Field(
        None, description="The querys' encoding", title='Encoding'
    )
    ExcludeNullOrEmptyElements: Optional[bool] = Field(
        None,
        description="The querys' exclude null or empty elements",
        title='ExcludeNullOrEmptyElements',
    )
    Groups_1: Optional[Groups] = Field(
        None, alias='Groups', description="The querys' groups", title='Group'
    )
    RootNodeName: Optional[str] = Field(
        None, description="The querys' root node name", title='RootNodeName'
    )
    SuppressMetricAttributes: Optional[bool] = Field(
        None,
        description="The querys' suppress metric attributes",
        title='SuppressMetricAttributes',
    )
    Variables_1: Optional[Variables] = Field(
        None, alias='Variables', description="The querys' variables", title='Variable'
    )


class Query(BaseModel):
    Query: Optional[Query1] = Field(None, title='Query')


class OutputItem1(BaseModel):
    field_MaxLength: Optional[str] = Field(
        None,
        alias='@MaxLength',
        description="The output bases' max length",
        title='@MaxLength',
    )
    field_Output: Optional[FieldOutput] = Field(
        None, alias='@Output', description="The output bases' output", title='@Output'
    )


class GroupItem1(BaseModel):
    field_GroupName: Optional[str] = Field(
        None,
        alias='@GroupName',
        description="The entity groups' group name",
        title='@GroupName',
    )
    field_ItemName: Optional[str] = Field(
        None,
        alias='@ItemName',
        description="The entity groups' item name",
        title='@ItemName',
    )
    field_LoopExpression: Optional[str] = Field(
        None,
        alias='@LoopExpression',
        description="The entity groups' loop expression",
        title='@LoopExpression',
    )
    field_Predicate: Optional[str] = Field(
        None,
        alias='@Predicate',
        description="The entity groups' predicate",
        title='@Predicate',
    )
    field_Selector: Optional[str] = Field(
        None,
        alias='@Selector',
        description="The entity groups' selector",
        title='@Selector',
    )
    field_UniqueKeyVariable: Optional[str] = Field(
        None,
        alias='@UniqueKeyVariable',
        description="The entity groups' unique key variable",
        title='@UniqueKeyVariable',
    )
    Condition: Optional[List[ConditionItem]] = Field(
        None, description="The entity groups' conditions", title='Condition'
    )
    Filter: Optional[List[FilterItem]] = Field(
        None, description="The entity groups' filters", title='Filter'
    )
    Order: Optional[List[OrderItem]] = Field(
        None, description="The entity groups' ordering", title='Order'
    )
    Output: Optional[List[OutputItem1]] = Field(
        None, description="The entity groups' outputs", title='Output'
    )


class Groups1(BaseModel):
    Group: Optional[List[GroupItem1]] = None


class Variables1(BaseModel):
    Variable: Optional[List[VariableItem]] = None


class ReportQuery(BaseModel):
    Encoding: Optional[str] = Field(
        None, description="The querys' encoding", title='Encoding'
    )
    ExcludeNullOrEmptyElements: Optional[bool] = Field(
        None,
        description="The querys' exclude null or empty elements",
        title='ExcludeNullOrEmptyElements',
    )
    Groups: Optional[Groups1] = Field(
        None, description="The querys' groups", title='Group'
    )
    RootNodeName: Optional[str] = Field(
        None, description="The querys' root node name", title='RootNodeName'
    )
    SuppressMetricAttributes: Optional[bool] = Field(
        None,
        description="The querys' suppress metric attributes",
        title='SuppressMetricAttributes',
    )
    Variables: Optional[Variables1] = Field(
        None, description="The querys' variables", title='Variable'
    )


class ReportDefinition1(BaseModel):
    Active: Optional[bool] = Field(
        None, description="The report definitions' active", title='Active'
    )
    Readonly: Optional[bool] = Field(
        None, description="The report definitions' readonly", title='Readonly'
    )
    ReportQuery_1: Optional[ReportQuery] = Field(
        None,
        alias='ReportQuery',
        description="The report definitions' report query",
        title='ReportQuery',
    )
    SupportedTransforms: Optional[str] = Field(
        None,
        description="The report definitions' supported transforms",
        title='SupportedTransforms',
    )
    Title: Optional[str] = Field(
        None, description="The report definitions' title", title='Title'
    )
    Version: Optional[str] = Field(
        None, description="The report definitions' version", title='Version'
    )


class ReportDefinition(BaseModel):
    ReportDefinition: Optional[ReportDefinition1] = Field(
        None, title='ReportDefinition'
    )


class ReportLine1(BaseModel):
    Description: Optional[str] = Field(
        None, description="The report lines' description", title='Description'
    )
    Generated: Optional[datetime] = Field(
        None, description="The report lines' generated", title='Generated'
    )
    TaxMonth: Optional[int] = Field(
        None, description="The report lines' tax month", title='TaxMonth'
    )
    TaxYear: Optional[int] = Field(
        None, description="The report lines' tax year", title='TaxYear'
    )
    Value: Optional[float] = Field(
        None, description="The report lines' value", title='Value'
    )


class ReportLine(BaseModel):
    ReportLine: Optional[ReportLine1] = Field(None, title='ReportLine')


class ReportingInstruction1(BaseModel):
    EndDate: Optional[date] = Field(
        None, description="The reporting instructions' end date", title='EndDate'
    )
    StartDate: Optional[date] = Field(
        None, description="The reporting instructions' start date", title='StartDate'
    )
    TaxMonth: Optional[int] = Field(
        None, description="The reporting instructions' tax month", title='TaxMonth'
    )
    TaxYear: Optional[int] = Field(
        None, description="The reporting instructions' tax year", title='TaxYear'
    )
    Value: Optional[float] = Field(
        None, description="The reporting instructions' value", title='Value'
    )


class ReportingInstruction(BaseModel):
    ReportingInstruction: Optional[ReportingInstruction1] = Field(
        None, title='ReportingInstruction'
    )


class Employer4(BaseModel):
    field_href: Optional[str] = Field(
        None, alias='@href', description="The links' href", title='@href'
    )
    field_rel: Optional[str] = Field(
        None, alias='@rel', description="The links' target type", title='@rel'
    )
    field_title: Optional[str] = Field(
        None, alias='@title', description="The links' title", title='@title'
    )


class LateReason(Enum):
    A = 'A'
    B = 'B'
    C = 'C'
    D = 'D'
    F = 'F'
    G = 'G'
    H = 'H'


class PaySchedule5(BaseModel):
    field_href: Optional[str] = Field(
        None, alias='@href', description="The links' href", title='@href'
    )
    field_rel: Optional[str] = Field(
        None, alias='@rel', description="The links' target type", title='@rel'
    )
    field_title: Optional[str] = Field(
        None, alias='@title', description="The links' title", title='@title'
    )


class RtiTransaction(BaseModel):
    field_href: Optional[str] = Field(
        None, alias='@href', description="The links' href", title='@href'
    )
    field_rel: Optional[str] = Field(
        None, alias='@rel', description="The links' target type", title='@rel'
    )
    field_title: Optional[str] = Field(
        None, alias='@title', description="The links' title", title='@title'
    )


class RtiJobInstruction1(BaseModel):
    EarlierTaxYear: Optional[int] = Field(
        None,
        description="The rti job instructions' earlier tax year",
        title='EarlierTaxYear',
    )
    Employer: Optional[Employer4] = Field(
        None, description="The rti job instructions' employer", title='Employer'
    )
    FinalSubmissionForYear: Optional[bool] = Field(
        None,
        description="The rti job instructions' final submission for year",
        title='FinalSubmissionForYear',
    )
    Generate: Optional[bool] = Field(
        None, description="The rti job instructions' generate", title='Generate'
    )
    HoldingDate: Optional[datetime] = Field(
        None, description="The rti job instructions' holding date", title='HoldingDate'
    )
    LateReason_1: Optional[LateReason] = Field(
        None,
        alias='LateReason',
        description="The rti job instructions' late reason",
        title='LateReason',
    )
    NoPaymentForPeriodFrom: Optional[date] = Field(
        None,
        description="The rti job instructions' no payment for period from",
        title='NoPaymentForPeriodFrom',
    )
    NoPaymentForPeriodTo: Optional[date] = Field(
        None,
        description="The rti job instructions' no payment for period to",
        title='NoPaymentForPeriodTo',
    )
    PaySchedule: Optional[PaySchedule5] = Field(
        None, description="The rti job instructions' pay schedule", title='PaySchedule'
    )
    PaymentDate: Optional[date] = Field(
        None, description="The rti job instructions' payment date", title='PaymentDate'
    )
    PeriodOfInactivityFrom: Optional[date] = Field(
        None,
        description="The rti job instructions' period of inactivity from",
        title='PeriodOfInactivityFrom',
    )
    PeriodOfInactivityTo: Optional[date] = Field(
        None,
        description="The rti job instructions' period of inactivity to",
        title='PeriodOfInactivityTo',
    )
    RtiTransaction_1: Optional[RtiTransaction] = Field(
        None,
        alias='RtiTransaction',
        description="The rti job instructions' rti transaction",
        title='RtiTransaction',
    )
    RtiType: Optional[str] = Field(
        None, description="The rti job instructions' rti type", title='RtiType'
    )
    SchemeCeased: Optional[date] = Field(
        None,
        description="The rti job instructions' scheme ceased",
        title='SchemeCeased',
    )
    TaxMonth: Optional[int] = Field(
        None, description="The rti job instructions' tax month", title='TaxMonth'
    )
    TaxYear: Optional[int] = Field(
        None, description="The rti job instructions' tax year", title='TaxYear'
    )
    Timestamp: Optional[datetime] = Field(
        None, description="The rti job instructions' timestamp", title='Timestamp'
    )
    Transmit: Optional[bool] = Field(
        None, description="The rti job instructions' transmit", title='Transmit'
    )


class RtiJobInstruction(BaseModel):
    RtiJobInstruction: Optional[RtiJobInstruction1] = Field(
        None, title='RtiJobInstruction'
    )


class RtiTransactionBase1(BaseModel):
    EmployerCore_1: Optional[EmployerCore] = Field(
        None,
        alias='EmployerCore',
        description="The rti transaction bases' employer core",
        title='EmployerCore',
    )
    RequestData: Optional[str] = Field(
        None, description="The rti transaction bases' request data", title='RequestData'
    )
    ResponseData: Optional[str] = Field(
        None,
        description="The rti transaction bases' response data",
        title='ResponseData',
    )
    RtiType: Optional[str] = Field(
        None, description="The rti transaction bases' rti type", title='RtiType'
    )
    TaxYear: Optional[int] = Field(
        None, description="The rti transaction bases' tax year", title='TaxYear'
    )
    Timestamp: Optional[datetime] = Field(
        None, description="The rti transaction bases' timestamp", title='Timestamp'
    )
    TransactionStatus_1: Optional[TransactionStatus] = Field(
        None,
        alias='TransactionStatus',
        description="The rti transaction bases' transaction status",
        title='TransactionStatus',
    )
    TransmissionDate: Optional[datetime] = Field(
        None,
        description="The rti transaction bases' transmission date",
        title='TransmissionDate',
    )


class RtiTransactionBase(BaseModel):
    RtiTransactionBase: Optional[RtiTransactionBase1] = Field(
        None, title='RtiTransactionBase'
    )


class BusinessType(Enum):
    SoleTrader = 'SoleTrader'
    Company = 'Company'
    Partnership = 'Partnership'
    Trust = 'Trust'


class PayFrequency5(Enum):
    Monthly = 'Monthly'
    Weekly = 'Weekly'


class TaxationStatus(Enum):
    Unmatched = 'Unmatched'
    Net = 'Net'
    Gross = 'Gross'


class SubContractor2(BaseModel):
    Address_1: Optional[Address] = Field(
        None,
        alias='Address',
        description="The sub contractors' address",
        title='Address',
    )
    BankAccount_1: Optional[BankAccount] = Field(
        None,
        alias='BankAccount',
        description="The sub contractors' bank account",
        title='BankAccount',
    )
    BusinessType_1: Optional[BusinessType] = Field(
        None,
        alias='BusinessType',
        description="The sub contractors' business type",
        title='BusinessType',
    )
    CompanyName: Optional[str] = Field(
        None, description="The sub contractors' company name", title='CompanyName'
    )
    CompanyRegistrationNumber: Optional[str] = Field(
        None,
        description="The sub contractors' company registration number",
        title='CompanyRegistrationNumber',
    )
    Deactivated: Optional[bool] = Field(
        None, description="The sub contractors' deactivated", title='Deactivated'
    )
    EffectiveDate: Optional[date] = Field(
        None, description="The sub contractors' effective date", title='EffectiveDate'
    )
    FirstName: Optional[str] = Field(
        None, description="The sub contractors' first name", title='FirstName'
    )
    Initials: Optional[str] = Field(
        None, description="The sub contractors' initials", title='Initials'
    )
    LastName: Optional[str] = Field(
        None, description="The sub contractors' last name", title='LastName'
    )
    MetaData: Optional[Dict[str, Any]] = Field(
        None, description="The sub contractors' meta data", title='MetaData'
    )
    MiddleName: Optional[str] = Field(
        None, description="The sub contractors' middle name", title='MiddleName'
    )
    NextRevisionDate: Optional[date] = Field(
        None,
        description="The sub contractors' next revision date",
        title='NextRevisionDate',
    )
    NiNumber: Optional[str] = Field(
        None, description="The sub contractors' ni number", title='NiNumber'
    )
    PartnershipName: Optional[str] = Field(
        None,
        description="The sub contractors' partnership name",
        title='PartnershipName',
    )
    PartnershipUniqueTaxReference: Optional[str] = Field(
        None,
        description="The sub contractors' partnership unique tax reference",
        title='PartnershipUniqueTaxReference',
    )
    PayFrequency: Optional[PayFrequency5] = Field(
        None, description="The sub contractors' pay frequency", title='PayFrequency'
    )
    PaymentMethod_1: Optional[PaymentMethod] = Field(
        None,
        alias='PaymentMethod',
        description="The sub contractors' payment method",
        title='PaymentMethod',
    )
    Region_1: Optional[Region] = Field(
        None, alias='Region', description="The sub contractors' region", title='Region'
    )
    Revision: Optional[int] = Field(
        None, description="The sub contractors' revision", title='Revision'
    )
    TaxationStatus_1: Optional[TaxationStatus] = Field(
        None,
        alias='TaxationStatus',
        description="The sub contractors' taxation status",
        title='TaxationStatus',
    )
    Telephone: Optional[str] = Field(
        None, description="The sub contractors' telephone", title='Telephone'
    )
    Territory_1: Optional[Territory] = Field(
        None,
        alias='Territory',
        description="The sub contractors' territory",
        title='Territory',
    )
    Title: Optional[str] = Field(
        None, description="The sub contractors' title", title='Title'
    )
    TradingName: Optional[str] = Field(
        None, description="The sub contractors' trading name", title='TradingName'
    )
    UniqueTaxReference: Optional[str] = Field(
        None,
        description="The sub contractors' unique tax reference",
        title='UniqueTaxReference',
    )
    VatRegistered: Optional[bool] = Field(
        None, description="The sub contractors' vat registered", title='VatRegistered'
    )
    VatRegistrationNumber: Optional[str] = Field(
        None,
        description="The sub contractors' vat registration number",
        title='VatRegistrationNumber',
    )
    VerificationDate: Optional[datetime] = Field(
        None,
        description="The sub contractors' verification date",
        title='VerificationDate',
    )
    VerificationNumber: Optional[str] = Field(
        None,
        description="The sub contractors' verification number",
        title='VerificationNumber',
    )
    WorksNumber: Optional[str] = Field(
        None, description="The sub contractors' works number", title='WorksNumber'
    )


class SubContractor1(BaseModel):
    SubContractor: Optional[SubContractor2] = Field(None, title='SubContractor')


class TaggedItem(BaseModel):
    field_href: Optional[str] = Field(
        None, alias='@href', description="The links' href", title='@href'
    )
    field_rel: Optional[str] = Field(
        None, alias='@rel', description="The links' target type", title='@rel'
    )
    field_title: Optional[str] = Field(
        None, alias='@title', description="The links' title", title='@title'
    )


class Tag1(BaseModel):
    Created: Optional[datetime] = Field(
        None, description="The tags' created", title='Created'
    )
    TaggedItem_1: Optional[TaggedItem] = Field(
        None,
        alias='TaggedItem',
        description="The tags' tagged item",
        title='TaggedItem',
    )
    Text: Optional[str] = Field(None, description="The tags' text", title='Text')


class Tag(BaseModel):
    Tag: Optional[Tag1] = Field(None, title='Tag')


class ThirdPartyJobInstruction1(BaseModel):
    EmployerHref: Optional[str] = Field(
        None,
        description="The third party job instructions' employer href",
        title='EmployerHref',
    )
    HoldingDate: Optional[datetime] = Field(
        None,
        description="The third party job instructions' holding date",
        title='HoldingDate',
    )
    InstructionType: Optional[str] = Field(
        None,
        description="The third party job instructions' instruction type",
        title='InstructionType',
    )
    MetaData: Optional[Dict[str, Any]] = Field(
        None,
        description="The third party job instructions' meta data",
        title='MetaData',
    )
    PayLoad: Optional[str] = Field(
        None, description="The third party job instructions' pay load", title='PayLoad'
    )


class ThirdPartyJobInstruction(BaseModel):
    ThirdPartyJobInstruction: Optional[ThirdPartyJobInstruction1] = Field(
        None, title='ThirdPartyJobInstruction'
    )


class ThirdPartyTransaction(RootModel[Any]):
    root: Any


class TransformDefinition1(BaseModel):
    Active: Optional[bool] = Field(
        None, description="The transform definitions' active", title='Active'
    )
    ContentType: Optional[str] = Field(
        None, description="The transform definitions' content type", title='ContentType'
    )
    Definition: Optional[str] = Field(
        None, description="The transform definitions' definition", title='Definition'
    )
    DefinitionType: Optional[str] = Field(
        None,
        description="The transform definitions' definition type",
        title='DefinitionType',
    )
    Readonly: Optional[bool] = Field(
        None, description="The transform definitions' readonly", title='Readonly'
    )
    SupportedReports: Optional[str] = Field(
        None,
        description="The transform definitions' supported reports",
        title='SupportedReports',
    )
    TaxYear: Optional[int] = Field(
        None, description="The transform definitions' tax year", title='TaxYear'
    )
    Title: Optional[str] = Field(
        None, description="The transform definitions' title", title='Title'
    )
    Version: Optional[str] = Field(
        None, description="The transform definitions' version", title='Version'
    )


class TransformDefinition(BaseModel):
    TransformDefinition: Optional[TransformDefinition1] = Field(
        None, title='TransformDefinition'
    )


class PermissionItem(BaseModel):
    field_href: Optional[str] = Field(
        None, alias='@href', description="The links' href", title='@href'
    )
    field_rel: Optional[str] = Field(
        None, alias='@rel', description="The links' target type", title='@rel'
    )
    field_title: Optional[str] = Field(
        None, alias='@title', description="The links' title", title='@title'
    )


class Permissions(BaseModel):
    Permission: Optional[List[PermissionItem]] = None


class Roles(BaseModel):
    Role: Optional[List[str]] = None


class User1(BaseModel):
    MetaData: Optional[Dict[str, Any]] = Field(
        None, description="The users' meta data", title='MetaData'
    )
    Permissions_1: Optional[Permissions] = Field(
        None,
        alias='Permissions',
        description="The users' permissions",
        title='Permission',
    )
    Roles_1: Optional[Roles] = Field(
        None, alias='Roles', description="The users' roles", title='Roles'
    )
    UserIdentifier: Optional[str] = Field(
        None, description="The users' user identifier", title='UserIdentifier'
    )


class User(BaseModel):
    User: Optional[User1] = Field(None, title='User')
